import type { Alumni } from "./types"

export const alumniData: Alumni[] = [
  {
    id: "1",
    name: "Emma Johnson",
    email: "emma.johnson@example.com",
    position: "Software Engineer",
    department: "Computer Science",
    graduationYear: "2020",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://github.com/emmajohnson", type: "GitHub" },
      { url: "https://linkedin.com/in/emmajohnson", type: "LinkedIn" },
      { url: "https://emmajohnson.dev", type: "Website" },
    ],
    location: "San Francisco, CA",
    company: "Google",
    skills: ["JavaScript", "React", "Node.js", "TypeScript"],
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    position: "Data Scientist",
    department: "Mathematics",
    graduationYear: "2018",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://linkedin.com/in/michaelchen", type: "LinkedIn" },
      { url: "https://github.com/michaelchen", type: "GitHub" },
    ],
    location: "New York, NY",
    company: "Amazon",
    skills: ["Python", "Machine Learning", "Data Analysis", "SQL"],
  },
  {
    id: "3",
    name: "Sophia Rodriguez",
    email: "sophia.rodriguez@example.com",
    position: "Marketing Director",
    department: "Business",
    graduationYear: "2015",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://instagram.com/sophiarod", type: "Instagram" },
      { url: "https://linkedin.com/in/sophiarodriguez", type: "LinkedIn" },
    ],
    location: "Miami, FL",
    company: "Meta",
    skills: ["Digital Marketing", "Social Media", "Content Strategy", "SEO"],
  },
  {
    id: "4",
    name: "James Wilson",
    email: "james.wilson@example.com",
    position: "Professor",
    department: "Physics",
    graduationYear: "1995",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://jameswilson.edu", type: "Website" },
      { url: "https://researchgate.net/jameswilson", type: "ResearchGate" },
    ],
    location: "Boston, MA",
    company: "MIT",
    skills: ["Quantum Physics", "Research", "Teaching", "Scientific Writing"],
  },
  {
    id: "5",
    name: "Olivia Taylor",
    email: "olivia.taylor@example.com",
    position: "Research Scientist",
    department: "Biology",
    graduationYear: "2019",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://researchgate.net/oliviataylor", type: "ResearchGate" },
      { url: "https://linkedin.com/in/oliviataylor", type: "LinkedIn" },
    ],
    location: "Seattle, WA",
    company: "Microsoft Research",
    skills: ["Genomics", "Bioinformatics", "R", "Python"],
  },
  {
    id: "6",
    name: "William Brown",
    email: "william.brown@example.com",
    position: "Financial Analyst",
    department: "Economics",
    graduationYear: "2017",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [{ url: "https://linkedin.com/in/williambrown", type: "LinkedIn" }],
    location: "Chicago, IL",
    company: "JP Morgan",
    skills: ["Financial Modeling", "Excel", "Data Analysis", "Risk Assessment"],
  },
  {
    id: "7",
    name: "Ava Martinez",
    email: "ava.martinez@example.com",
    position: "UX Designer",
    department: "Design",
    graduationYear: "2021",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://behance.net/avamartinez", type: "Behance" },
      { url: "https://dribbble.com/avamartinez", type: "Dribbble" },
      { url: "https://avamartinez.design", type: "Website" },
    ],
    location: "Austin, TX",
    company: "Apple",
    skills: ["UI/UX", "Figma", "Adobe XD", "Prototyping", "User Research"],
  },
  {
    id: "8",
    name: "Ethan Lee",
    email: "ethan.lee@example.com",
    position: "Product Manager",
    department: "Computer Science",
    graduationYear: "2016",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://medium.com/@ethanlee", type: "Medium" },
      { url: "https://linkedin.com/in/ethanlee", type: "LinkedIn" },
    ],
    location: "San Jose, CA",
    company: "Netflix",
    skills: ["Product Strategy", "Agile", "User Stories", "Roadmapping"],
  },
  {
    id: "9",
    name: "Isabella Garcia",
    email: "isabella.garcia@example.com",
    position: "Architect",
    department: "Engineering",
    graduationYear: "2014",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://dribbble.com/isabellagarcia", type: "Dribbble" },
      { url: "https://isabellagarcia.com", type: "Website" },
    ],
    location: "Portland, OR",
    company: "Nike",
    skills: ["AutoCAD", "Revit", "3D Modeling", "Sustainable Design"],
  },
  {
    id: "10",
    name: "Noah Clark",
    email: "noah.clark@example.com",
    position: "Doctor",
    department: "Medicine",
    graduationYear: "2010",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://doximity.com/noahclark", type: "Doximity" },
      { url: "https://linkedin.com/in/noahclark", type: "LinkedIn" },
    ],
    location: "Baltimore, MD",
    company: "Johns Hopkins Hospital",
    skills: ["Surgery", "Patient Care", "Medical Research", "Diagnostics"],
  },
  {
    id: "11",
    name: "Charlotte Lewis",
    email: "charlotte.lewis@example.com",
    position: "Lawyer",
    department: "Law",
    graduationYear: "2013",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://linkedin.com/in/charlottelewis", type: "LinkedIn" },
      { url: "https://charlottelewis.law", type: "Website" },
    ],
    location: "Washington, DC",
    company: "Lewis & Partners",
    skills: ["Corporate Law", "Contract Negotiation", "Legal Research", "Litigation"],
  },
  {
    id: "12",
    name: "Benjamin Walker",
    email: "benjamin.walker@example.com",
    position: "Professor",
    department: "History",
    graduationYear: "1990",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://academia.edu/benjaminwalker", type: "Academia" },
      { url: "https://benjaminwalker.edu", type: "Website" },
    ],
    location: "Philadelphia, PA",
    company: "University of Pennsylvania",
    skills: ["Historical Research", "Teaching", "Publishing", "Public Speaking"],
  },
  {
    id: "13",
    name: "Amelia Hall",
    email: "amelia.hall@example.com",
    position: "Journalist",
    department: "Communications",
    graduationYear: "2012",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://medium.com/@ameliahall", type: "Medium" },
      { url: "https://twitter.com/ameliahall", type: "Twitter" },
      { url: "https://ameliahall.com", type: "Website" },
    ],
    location: "Los Angeles, CA",
    company: "LA Times",
    skills: ["Investigative Journalism", "Copywriting", "Editing", "Interviewing"],
  },
  {
    id: "14",
    name: "Lucas Young",
    email: "lucas.young@example.com",
    position: "Software Engineer",
    department: "Computer Science",
    graduationYear: "2022",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://github.com/lucasyoung", type: "GitHub" },
      { url: "https://linkedin.com/in/lucasyoung", type: "LinkedIn" },
      { url: "https://lucasyoung.dev", type: "Website" },
    ],
    location: "Denver, CO",
    company: "Salesforce",
    skills: ["Java", "Spring Boot", "Microservices", "AWS"],
  },
  {
    id: "15",
    name: "Mia Allen",
    email: "mia.allen@example.com",
    position: "Psychologist",
    department: "Psychology",
    graduationYear: "2011",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://psychologytoday.com/miaallen", type: "Psychology Today" },
      { url: "https://miaallen.com", type: "Website" },
    ],
    location: "Minneapolis, MN",
    company: "Allen Therapy",
    skills: ["Cognitive Behavioral Therapy", "Counseling", "Mental Health", "Assessment"],
  },
  {
    id: "16",
    name: "Henry King",
    email: "henry.king@example.com",
    position: "Entrepreneur",
    department: "Business",
    graduationYear: "2008",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://henryking.com", type: "Website" },
      { url: "https://linkedin.com/in/henryking", type: "LinkedIn" },
      { url: "https://twitter.com/henryking", type: "Twitter" },
    ],
    location: "Atlanta, GA",
    company: "King Ventures",
    skills: ["Business Development", "Fundraising", "Leadership", "Strategic Planning"],
  },
  {
    id: "17",
    name: "Evelyn Wright",
    email: "evelyn.wright@example.com",
    position: "Researcher",
    department: "Chemistry",
    graduationYear: "2015",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://researchgate.net/evelynwright", type: "ResearchGate" },
      { url: "https://linkedin.com/in/evelynwright", type: "LinkedIn" },
    ],
    location: "Raleigh, NC",
    company: "Duke University",
    skills: ["Analytical Chemistry", "Lab Research", "Data Analysis", "Scientific Writing"],
  },
  {
    id: "18",
    name: "Alexander Scott",
    email: "alexander.scott@example.com",
    position: "Professor",
    department: "Mathematics",
    graduationYear: "2005",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://mathworld.wolfram.com/alexanderscott", type: "MathWorld" },
      { url: "https://alexanderscott.edu", type: "Website" },
    ],
    location: "Princeton, NJ",
    company: "Princeton University",
    skills: ["Number Theory", "Mathematical Research", "Teaching", "Academic Publishing"],
  },
  {
    id: "19",
    name: "Harper Green",
    email: "harper.green@example.com",
    position: "Graphic Designer",
    department: "Arts",
    graduationYear: "2019",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://behance.net/harpergreen", type: "Behance" },
      { url: "https://dribbble.com/harpergreen", type: "Dribbble" },
      { url: "https://instagram.com/harpergreen.design", type: "Instagram" },
    ],
    location: "Nashville, TN",
    company: "Freelance",
    skills: ["Adobe Creative Suite", "Branding", "Typography", "Illustration"],
  },
  {
    id: "20",
    name: "Daniel Adams",
    email: "daniel.adams@example.com",
    position: "Civil Engineer",
    department: "Engineering",
    graduationYear: "2017",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://linkedin.com/in/danieladams", type: "LinkedIn" },
      { url: "https://danieladams.com", type: "Website" },
    ],
    location: "Houston, TX",
    company: "Adams Engineering",
    skills: ["Structural Design", "Project Management", "AutoCAD", "Construction Planning"],
  },
  {
    id: "21",
    name: "Abigail Baker",
    email: "abigail.baker@example.com",
    position: "Teacher",
    department: "Education",
    graduationYear: "2014",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://teachers.io/abigailbaker", type: "Teachers.io" },
      { url: "https://linkedin.com/in/abigailbaker", type: "LinkedIn" },
    ],
    location: "Phoenix, AZ",
    company: "Phoenix Public Schools",
    skills: ["Curriculum Development", "Classroom Management", "Special Education", "Assessment"],
  },
  {
    id: "22",
    name: "Matthew Nelson",
    email: "matthew.nelson@example.com",
    position: "Accountant",
    department: "Business",
    graduationYear: "2016",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [{ url: "https://linkedin.com/in/matthewnelson", type: "LinkedIn" }],
    location: "Dallas, TX",
    company: "Deloitte",
    skills: ["Financial Reporting", "Tax Planning", "Auditing", "Bookkeeping"],
  },
  {
    id: "23",
    name: "Elizabeth Carter",
    email: "elizabeth.carter@example.com",
    position: "Nurse",
    department: "Medicine",
    graduationYear: "2018",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://nursingnetwork.com/elizabethcarter", type: "Nursing Network" },
      { url: "https://linkedin.com/in/elizabethcarter", type: "LinkedIn" },
    ],
    location: "Cleveland, OH",
    company: "Cleveland Clinic",
    skills: ["Patient Care", "Medical Procedures", "Critical Care", "Healthcare Management"],
  },
  {
    id: "24",
    name: "Joseph Mitchell",
    email: "joseph.mitchell@example.com",
    position: "Software Developer",
    department: "Computer Science",
    graduationYear: "2020",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://github.com/josephmitchell", type: "GitHub" },
      { url: "https://linkedin.com/in/josephmitchell", type: "LinkedIn" },
      { url: "https://josephmitchell.dev", type: "Website" },
    ],
    location: "Seattle, WA",
    company: "Amazon",
    skills: ["Python", "Django", "AWS", "Docker", "CI/CD"],
  },
  {
    id: "25",
    name: "Sofia Perez",
    email: "sofia.perez@example.com",
    position: "Marketing Manager",
    department: "Business",
    graduationYear: "2013",
    avatar: "/placeholder.svg?height=40&width=40",
    portfolios: [
      { url: "https://linkedin.com/in/sofiaperez", type: "LinkedIn" },
      { url: "https://sofiaperez.com", type: "Website" },
    ],
    location: "Miami, FL",
    company: "Coca-Cola",
    skills: ["Brand Management", "Marketing Strategy", "Campaign Planning", "Analytics"],
  },
]
